### ISSUE TITLE
overlays broken with error 404: Not Found

### ISSUE THREAD

**Issue by Pleasuremanrx** [TheChrisK/Kometa#5]
https://raw.githubusercontent.com/TheChrisK/PMM/main/overlays/network-top-left/<<key>>.png
https://raw.githubusercontent.com/TheChrisK/PMM/main/overlays/audio-top-left-45deg/<<key>>.png
they error when visited 404: Not Found

it appears the audio and network overlays no longer work

![Image](https://github.com/user-attachments/assets/eaa81535-390c-49f0-b8df-0257680b811c)

**Comment by TheChrisK** [comment]
Ill need a log output.

**Comment by Pleasuremanrx** [comment]
[meta.log](https://github.com/user-attachments/files/20660104/meta.log)

I can provide one if necessary but the urls raw.githubusercontent seem to be broken they lead to 404 error or 400: Invalid request if you try to go to them individually in browser can you replicate/reproduce that?


The media stinger works it's the audio codec and the network ribbon i believe no longer work the ribbon/strip that says cancelled or returning though seems to still work.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by TheChrisK** [comment]
The raw URL still works. The part that's failing is the `<<key>>` which is dependent on the studio or network involved. If it's one of those one-off studios, or one with special characters, it might fail.

For example: https://raw.githubusercontent.com/TheChrisK/PMM/main/overlays/network-top-left/ABC.png and
https://raw.githubusercontent.com/TheChrisK/PMM/refs/heads/main/overlays/audio-top-left/atmos.png still works.

Is there a specific show it's failing on or everything?

**Comment by Pleasuremanrx** [comment]
No it's the more popular ones which is has me scratching my head

Yes I tried the abc one and it didnt error in the browser weird

But it's not being applied to the library

I'ma try removing all overlays then redoing them to see if that works I appreciate your assistance.

I also have
Disney +
Nickelodeon
Netflix
Hulu
Paramount+
PBS
Peacock
Prime video
WB
SYFY
NBC

None are showing in top left like they use to only the ribbon airing

Did you see anything in the log file out the ordinary?

It's not that big a deal I switched to another but just want to say thanks yours is where I got my start and learned some yaml.

The reflecting networks covers are 🔥 as well man


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by TheChrisK** [comment]
Is the overlay config in your `config.yml` or in a separate `network.yml` file? Also, not that it probably matters, but you are not on the latest version of Kometa.

I see the errors but I can't figure out why it's not working for you. Personally, my setup is the same except my files and references to them are local. You could try copying all the overlay files to your `overlays` directory and use the file paths instead of the git URLs.

```yaml
    overlay_files:
    - remove_overlays: false
    - file: config/overlays/Top.yml
    - file: config/overlays/Status.yml
    - default: network
      template_variables:
        horizontal_align: left
        horizontal_offset: 0
        vertical_offset: 0
        vertical_align: top
        back_width: 1000
        back_height: 1500
        file: config/overlays/network-top-left/<<key>>.png
        back_color: 00
```
